version: "2"

services:
  doris-fe:
    hostname: fe
    build:
      context: ./
      dockerfile: ./fe/Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/tis/doris-fe:1.1.3
    links:
      - doris-be
    #ports:
    #  - 9031:9030
    #  - 8031:8030
    depends_on:
      - doris-be
    network_mode: host  

  doris-be:
    hostname: be
    build:
      context: ./
      dockerfile: ./be/Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/tis/doris-be:1.1.3
    network_mode: host
#    deploy:
#      mode: replicated
#      replicas: 3
